name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: node:lts
    strategy:
      matrix:
        os: [ubuntu-18.04] # add an array of os's to test [macos-latest, windows-latest]
        node-version: [12.x]

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn
      
      - name: Build
        run: |
          yarn build