name: E2E on Chrome
on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config: pageLoadTimeout=100000,watchForFileChanges=false
          build: npm run build
          command-prefix: cross-env NODE_ENV=test nyc --check-coverage --branches=100 --functions=100 --lines=100 --statements=100
          start: npm start
          record: true
        env:
          VUE_APP_API_URL: https://api.local/api